version: '3.8'

services:
  query-generation-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: query-generation-mcp
    image: query-generation-agent:latest
    ports:
      - "8081:8081"
    
    # Load environment variables from .env file
    env_file:
      - .env
    
    # Override specific variables for containerized deployment
    environment:
      - MCP_TRANSPORT=http  # Use HTTP for containerized deployment
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8081
    
    volumes:
      # Optional: Mount GCP credentials if using service account
      # - ~/.config/gcloud:/home/appuser/.config/gcloud:ro
      # - /path/to/service-account-key.json:/app/credentials/key.json:ro
      - ./logs:/app/logs
    
    # Health check against MCP /health endpoint
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8081/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

